# pyproject.toml

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = """
    --cov=gitutils
    --cov-report=term-missing
    --cov-fail-under=35
    -v
"""

[tool.coverage.run]
source = ["gitutils"]
omit = [
    "*/tests/*",
    "*/.venv/*",
    "*/__pycache__/*"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "from typing import TYPE_CHECKING",
    "if TYPE_CHECKING:",
    "pass",
    "plt.show()", # Exclude interactive plotting calls
    'print(.*)'   # Exclude simple print statements
]